# Generated by Django 4.2.1 on 2023-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiasTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_A', models.JSONField()),
                ('point_for_optionA', models.IntegerField()),
                ('option_B', models.JSONField()),
                ('point_for_optionB', models.IntegerField()),
                ('option_C', models.JSONField()),
                ('point_for_optionC', models.IntegerField()),
                ('option_D', models.JSONField()),
                ('point_for_optionD', models.IntegerField()),
                ('test_for_bias_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('possibility_biases_1', models.IntegerField()),
                ('possibility_biases_2', models.IntegerField()),
                ('possibility_biases_3', models.IntegerField()),
                ('possibility_biases_4', models.IntegerField()),
                ('possibility_biases_5', models.IntegerField()),
            ],
        ),
    ]
