# Generated by Django 4.2.1 on 2023-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biastestquestion',
            name='option_A',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='biastestquestion',
            name='option_B',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='biastestquestion',
            name='option_C',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='biastestquestion',
            name='option_D',
            field=models.TextField(),
        ),
    ]
