# Generated by Django 4.2.1 on 2023-05-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0002_alter_biastestquestion_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biastestquestion',
            name='question_bank_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biastestquestion',
            name='question_description',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
