# Generated by Django 4.2.1 on 2023-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0005_biastestquestion_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biastestquestion',
            name='question_description',
            field=models.TextField(default='default'),
        ),
    ]
