# Generated by Django 4.2.1 on 2023-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0007_remove_biastestquestion_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
