# Generated by Django 4.2.1 on 2023-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0008_alter_user_possibility_biases_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='possibility_biases_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
