# Generated by Django 4.2.1 on 2023-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0009_alter_user_possibility_biases_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
