# Generated by Django 4.2.1 on 2023-06-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0010_remove_user_id_user_password_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
