# Generated by Django 4.2.1 on 2023-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_test', '0011_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias_index', models.IntegerField()),
                ('head', models.TextField()),
                ('brief', models.TextField()),
                ('img', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='https://th.bing.com/th/id/R.9406b6733452f77e2508e8c99d7706cc?rik=hiO5yYVXcHnVbg&riu=http%3a%2f%2fpic.2265.com%2fupload%2f2017-4%2f20174261525268918.png&ehk=eg4iXWUV3vwQGawiPmx0EyrIBNr9JtqBU%2bcu49moe0c%3d&risl=&pid=ImgRaw&r=0'),
        ),
    ]
